#ifndef COMMON_WORLD_TERRAIN_TYPE_H
#define COMMON_WORLD_TERRAIN_TYPE_H

enum class TerrainType {
    GRASS,
    WATER,
    DIRT,
    STONE,
    SAND,
    WOOD,
    DUNGEON_ENTRANCE_1,
    DUNGEON_FLOOR_1,
    DUNGEON_WALL_1,
    DUNGEON_ENTRANCE_2,
    DUNGEON_FLOOR_2,
    DUNGEON_WALL_2,
    CITY_FLOOR_1,
    CITY_WALL_1,
    CITY_FLOOR_2,
    CITY_WALL_2
};

#endif
