# ============================================================
#                      Argentum Online
#                            Map
# ============================================================

# ------------------------------------------------------------
#   Map Characters:
#   #  = stone (blocking)
#   .  = grass (non blocking)
#   T  = tree (blocking)
#   ,  = dirt (non blocking)
#   s  = sand (non blocking)
#   ~  = water (blocking)
#   d  = dungeon floor 1 / E = dungeon entrance 1 / D = dungeon wall 1
#   W  = wood (dock/bridge, non blocking)
#   *  = dungeon floor 2 / < = dungeon entrance 2 / P = dungeonwall 2
#   -  = city floor 1 / C = wall 1
#   :  = city floor 2 / A = wall 2
# ------------------------------------------------------------

[map]
width = 100
height = 70

rows = [
  "####################################################################################################",
  "#CCCCCCCCCCCCCCCCCCCCCC..T...................T..TTTT...T.....TTTTT..............DDDDDDDDDDDDDDDDDDD#",
  "#C--------------------C....ssssssssssssss......T.TTT.T..T.T.TTTTTT....T.........DDDDdddDDDDDDDDDDDD#",
  "#C--------------------C..ss~~~~~~~~~~~~~ss.......TT........T.TTTTT..............DDDDddddDDDDDDDDDDD#",
  "#C--------------------C.ss~~~~~~~~~~~~~~~ssTTT........T..T..#...................DDDddddddDdddddddDD#",
  "#C--------------------Css~~~~~~~~~~~~~~~~~ssTT..T.T.......T.............#.......DDDddddddDdddddddDD#",
  "#C--------------------Cs~~~~~~~~~~~~~~~~~~~sTT......T..#.........#..............DDDDDDdddDdddddddDD#",
  "#C--------------------Cs~~~~~~~~~~~~~~~~~~~sTT.................................EddddddddddddDdddddD#",
  "#C--------------------Cs~~~~~~~~~~~~~~~~~~~s..................................,,,DDdddddddDDdddddDD#",
  "#C--------------------Cs~~~~~~~~~~~~~~~~~~~s.....TTT..........................,,,DDddddddDDDdddddDD#",
  "#C--------------------Cs~~~~~~~~~~~~~~~~~~~s....TTTT..........................,,,DDddddddDDDdddDDDD#",
  "#C--------------------Cs~~~~~~~~~~~~~~~~~~~s....TTTT.#.............#..........,,,DDdddDDDDdddddddDD#",
  "#C--------------------Cs~~~~~~~~~~~~~~~~~~~s....TTTT..........................,,,DDdddddddddddddddD#",
  "#C--------------------C...T.........~~~~~~ss....TTTT..........................,,,DDddddddddddddddDD#",
  "#C--------------------C.....T.......~~~~~~s...................................,,,DDDDDDDDDDDDDDDDDD#",
  "#C--------------------C..T......T...~~~~~~s............#.........#............,,,DDDDDDDDDDDDDDDDDD#",
  "#C--------------------C.............~~~~~~s...................................,,,..................#",
  "#CCCCCCC,,,,,,CCCCCCCCC.............~~~~~~s.................#.................,,,..................#",
  "#......,,,,,,,ss~~~~~~~~~~~~~~~~~~~~~~~~~~s........T..........................,,,..............TTTT#",
  "#......,,,,,,,~~~~~~~~~~~~~~~~~~~~~~~~~~~~s.............T.....................,,,..............TTTT#",
  "#......,,,,,,,~~~~~~~~~~~~~~~~~~~~~~~~~~~ss..........T..........####..........,,,..............TTTT#",
  "#......,,,,,,,~~~~~~~~~~~~~~~~~~~~~~~~~~ss.........T...T..T.....####..........,,,..............TTTT#",
  "#......,,,,,,,~~~~~~~~~~~~~~~~~~~~~~ss#####..........T..T.T......##...........,,,.........TTTTT....#",
  "#......,,,,,,,~~~~~~~~~~~~~~~~~ssssss~#~~~#............T.T.......##...........,,,.........TTTTT....#",
  "#......,,,,,,,ss~~~~~~~~~~~~~sss...sss#~~~#......................##...........,,,.........TTTTT....#",
  "#......,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,~~#~~~,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#",
  "#.T....,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,####~~,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#",
  "#......,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,s###~~ss..........................................,,,TTTTT....#",
  "#...........,,,.......................sss~~~~ss............................T...........,,,.........#",
  "#.T.........,,,..........................s~~~~~s.......................................,,,.........#",
  "#....T......,,,...........................ss~~~~s.................................T....T,,.........#",
  "#...........,,,.............................ss~~~ss....................................,,,.........#",
  "#...........,,,...............................s~~~~s...................................,,,.........#",
  "#...T...T...,,,................................s~~~~s.................................T,,,.........#",
  "#...#####~..,,,.................................s~~~~ss................................,,,.........#",
  "#...###.#~~.,,,...................TT..........TTTss~~~~s...TT..........................,,,.........#",
  "#..T#.#####~,,,.........T.........TT.............sss~~~~s.TTT.........##...............,,,.........#",
  "#...#####.#~,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,WWWWWWWWW,,,,,,,,,,#,,,,,,,,,,,,,,,,,,,.....T...#",
  "#..T####.##~,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,WWWWWWWWWW,,,,#####,,,###,,,,,,,,,,,,,,..T....T.#",
  "#....Ts###~.,,,...sss...TTTTTTT............T.TT......s~~~~~ss.......T#TT.#.#...........,,,.........#",
  "#..~.~~~~~~.,,,..sssssT..TTTTTT...........TT..........s~~~~~s.......TTTT.#...........T.,,T...T.....#",
  "#.~~~~~~~s.s,,,...ss~s....TTTTTT..........TT.........T.s~~~~~s......TTTT...............,,,....T....#",
  "#.~~~~~~~.ss,,s....ssssT...TTTT........T..T.........TTTTs~~~~~s......TT..............TT,,,T........#",
  "#..~~~~...ss,,.ss...ssssTT............TT...........TTTTTTs~~~~~s.......................,,,.T.......#",
  "#...~~~s...s,,ssss...sss....T......TTTTT...........TTTTTT.s~~~~~s......................,,,...T.....#",
  "#...~~s.T...,,sss~s.ss~s.......T.TTTTTT.............TTTTTT.s~~~~~ss..................T.,,,T........#",
  "#..T.s..ss..,,ssss...ssT..T......TTTTTT.................TTTTs~~~~~~s................T.T,,,.........#",
  "#......ssss.,,~s.............T...TTTTT..........TT.......TTTTss~~~~~ss.................,,T.........#",
  "#......ss~s.,,s..................TTTTT.........TTT........TTT..ss~~~~~ss.............T.,,,.T.......#",
  "#......sss..,,.................................T............T....ss~~~~~ss.............,,,.........#",
  "#.....ssss..,,....................................................Ts~~~~~~s............,,,.........#",
  "#.....ss~s..,,......................................................##~~~~~ss..........,,,.........#",
  "#......ss...,,......................................................##ss~~~~~AAAAAAAAAA......AAAAAA#",
  "#....T......,,...................T..................................##..ss~~~A::::::::::::::::::::A#",
  "#...PPPPPPPPPPPPPPPPPP......T.T.................T.T.......................ss~A::::::::::::::::::::A#",
  "#...P****************P..####.###T...................T...................T...sA::::::::::::::::::::A#",
  "#.T.P***PPPPPP*P*P***P..#.#..T.#.................T...........................A::::::::::::::::::::A#",
  "#...P********P*P*PPPPP..#.....##...................T................##.......A::::::::::::::::::::A#",
  "#..TPPPPP****PPPP****P..............................................##........::::::::::::::::::::A#",
  "#...P********P***P***P.................T............................##........::::::::::::::::::::A#",
  "#...P***PPPPPP***P***P................................T.............##........::::::::::::::::::::A#",
  "#..TP**************P**<..................####....#..................##........::::::::::::::::::::A#",
  "#...PPPPP**PPPP**P***P.....................###..##...###.....................A::::::::::::::::::::A#",
  "#..TP**********P*PPPPP..................T...T###......#......................A::::::::::::::::::::A#",
  "#...P****P*PPPPP*****P....................T......##.#........................A::::::::::::::::::::A#",
  "#.T.P*****P**********P..................T...T...#..#.........................A::::::::::::::::::::A#",
  "#...PPPPPPPPPPPPPPPPPP.........................##....T.......................A::::::::::::::::::::A#",
  "#..T........................................T......T.........................A::::::::::::::::::::A#",
  "#...T........................................................................AAAAAAAAAAAAAAAAAAAAAA#",
  "####################################################################################################",
]

#  ---------------------------------
# Zones
# ---------------------------------
 
[[zones]]
type = "city"
name = "Ullathorpe"
priest_x = 3
priest_y = 8
merchant_x = 19
merchant_y = 9
banker_x = 11
banker_y = 14
x = 1
y = 1
width = 22
height = 17
 
[[zones]]
type = "city"
name = "Mireld"
priest_x = 95
priest_y = 57
merchant_x = 95
merchant_y = 62
banker_x = 87
banker_y = 66
x = 77
y = 52
width = 22
height = 17
 
[[zones]]
type = "dungeon"
name = "Caverna Laberinto de Sombras"
entrance_x = 79
entrance_y = 7
x = 80
y = 1
width = 19
height = 15
 
[[zones]]
type = "dungeon"
name = "Mazmorra de Abaddon"
entrance_x = 22
entrance_y = 61
x = 4
y = 54
width = 18
height = 13
 
# ---------------------------------
# Ground Items
# ---------------------------------
 
# Item en la orilla del lago 
 
[[ground_items]]
type = "item"
name = "Arco simple"
x = 24
y = 4
 
# Dentro de Ullathorpe (ciudad 1) 
 
[[ground_items]]
type = "item"
name = "Espada"
x = 4
y = 4
 
[[ground_items]]
type = "item"
name = "Túnica azul"
x = 8
y = 9
 
[[ground_items]]
type = "item"
name = "Escudo de tortuga"
x = 15
y = 14
 
# Orilla del lago (este de Ullathorpe) 
 
[[ground_items]]
type = "item"
name = "Capucha"
x = 43
y = 6
 
[[ground_items]]
type = "item"
name = "Martillo"
x = 48
y = 4
 
[[ground_items]]
type = "gold"
amount = 80
x = 50
y = 7
 
# Norte del mapa (bosque entre ciudades) 
 
[[ground_items]]
type = "item"
name = "Arco compuesto"
x = 58
y = 3
 
[[ground_items]]
type = "item"
name = "Flauta élfica"
x = 70
y = 5
 
# Camino principal (zona central) 
 
[[ground_items]]
type = "item"
name = "Vara de fresno"
x = 25
y = 38
 
[[ground_items]]
type = "item"
name = "Báculo nudoso"
x = 55
y = 38
 
[[ground_items]]
type = "item"
name = "Pocion de vida"
quantity = 2
x = 35
y = 37
 
[[ground_items]]
type = "item"
name = "Pocion de mana"
quantity = 2
x = 65
y = 37
 
[[ground_items]]
type = "gold"
amount = 350
x = 45
y = 38
 
# Ruinas centrales

[[ground_items]]
type = "item"
name = "Espada"
x = 7
y = 33
 
[[ground_items]]
type = "gold"
amount = 500
x = 5
y = 33
 
# Zona sur (cerca de Mazmorra) 
 
[[ground_items]]
type = "item"
name = "Hacha"
x = 24
y = 54
 
[[ground_items]]
type = "item"
name = "Armadura de cuero"
x = 35
y = 57
 
[[ground_items]]
type = "item"
name = "Sombrero mágico"
x = 20
y = 50
 
[[ground_items]]
type = "gold"
amount = 400
x = 30
y = 52
 
# Dungeon 1 treasure 
 
[[ground_items]]
type = "item"
name = "Casco de hierro"
x = 85
y = 4
 
[[ground_items]]
type = "item"
name = "Escudo de hierro"
x = 91
y = 6
 
[[ground_items]]
type = "item"
name = "Pocion de vida"
quantity = 5
x = 84
y = 8
 
[[ground_items]]
type = "gold"
amount = 1000
x = 93
y = 11
 
# Dungeon 2 treasure
 
[[ground_items]]
type = "item"
name = "Báculo engarzado"
x = 8
y = 55
 
[[ground_items]]
type = "item"
name = "Armadura de placas"
x = 14
y = 57
 
[[ground_items]]
type = "item"
name = "Pocion de vida"
quantity = 8
x = 10
y = 61
 
[[ground_items]]
type = "gold"
amount = 2500
x = 16
y = 62