# ============================================================
#                      Argentum Online 
#                            Map
# ============================================================

[map]
width = 40
height = 25

rows = [
  "########################################",
  "#................................T.....#",
  "#.####........####.....................#",
  "#.#..#.............................T...#",
  "#.#..#.........,,,,,,......##..........#",
  "#.####.........,,,,,,..................#",
  "#..............,,,,,,..................#",
  "#....T........~~~~~............ssssssss#",
  "#............~~~~~~............ssssssss#",
  "#...........~~~~~~~............ssssssss#",
  "#..........~~~~~~~~............ssssssss#",
  "#.........~~~~~~~~~............ssssssss#",
  "#.........~~~~~~~~~............ssssssss#",
  "#..........~~~~~~~~............ssssssss#",
  "#...........~~~~~~~............ssssssss#",
  "#.....T......~~~~~~.......####.ssssssss#",
  "#.............~~~~~.......#..#.ssssssss#",
  "#.............~~~~~.......#..#.ssssssss#",
  "#.............~~~~~.......####.ssssssss#",
  "#....,,,,,,,,,,,,,,,,,,,,,.....ssssssss#",
  "#....,,,,,,,,,,,,,,,,,,,,,.....ssssssss#",
  "#.....####.............TT......ssssssss#",
  "#......................TT......ssssssss#",
  "#......................................#",
  "########################################",
]
